name: belajar_dart_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

publish_to: none

# Add regular dependencies here.
dependencies:
  belajar_dart_library_2023:
    git:
      url: git@github.com:razzytirta/belajar_dart_library_2023.git
      ref: 1.5.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
